public class customizationForMerchandise
{

    private final Merchandise__c merchandise;


    public customizationForMerchandise(ApexPages.StandardController controller) { //test commit

    }   
      
    public Merchandise__c getMerchandise() {
        return merchandise;   
    }

    Public String name{get;set;}
    Public String Price{get;set;}
    Public String Quantity{get;set;}
    
    public String SearchData(){
    
   return null;
   }
}